export default {
  AUTHENTICATE: 'AUTHENTICATE',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  OPEN_TO_PLAYERS: 'OPEN_TO_PLAYERS',
  OPENED_TO_PLAYERS: 'OPENED_TO_PLAYERS',
  CLOSE_TO_PLAYERS: 'CLOSE_TO_PLAYERS',
  CLOSED_TO_PLAYERS: 'CLOSED_TO_PLAYERS',
}
